version: '3'
services:
    postgres:
        image: postgres:14
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: sMeZtEgBcAskbhxp
            TZ: America/Sao_Paulo
        volumes:
            - ./dados:/var/lib/postgresql/data
        ports:
            - 127.0.0.1:5449:5432
        restart: always

    redis:
       image: redis
       restart: always
       command: redis-server --save 3600 1
       volumes:
           - ./cache:/data
       ports:
           - 127.0.0.1:6399:6379

    challenge:
        image: desafiotruther-challenge:v1.00
        volumes:
            - ./logs/challenge:/app/logs
        environment:
            - TZ=America/Sao_Paulo
        restart: always
        ports:
            - 8989:8989